### ISSUE TITLE
Redemption prayer 1.0 changes

### ISSUE THREAD

**Issue by catharsis71** [Silberdrachi/CanIIdle#10]
It seems like the Redemption prayer is now relevant

``` Changed the Redemption effect to: +20% Auto Eat Hitpoints Limit. Was previously: Heal +20% HP when your hitpoints fall below 10%.```

So it seems like there should be a checkbox in Advanced for this like there is for the Wasteful Ring

I'm not sure exactly how it works as the auto-eat tooltip doesn't visibly change but I assume it probably invisibly changes the Auto Eat 3 threshold from 40% to 48%?

**Comment by Silberdrachi** [comment]
This is raising the limit at which your autoeat would eat to. For example if you have AE3 and trigger at 40%, it would eat to 80%, with the buff it would eat to 100%. This doesn't change the lower limit bound at which the autoeat triggers. which means it doesn't affect idle ability because its not changing the threshold of when you eat.
