### ISSUE TITLE
Calculation on Water God Dungeon

### ISSUE THREAD

**Issue by Skordatura** [Silberdrachi/CanIIdle#19]
Hi, 
Thanks so much for making this calculator, it's been very helpful! I did notice though that the requirement for the Water God Dungeon seems odd and might be incorrect. In my case (https://silberdrachi.github.io/CanIIdle/?totalHealth=1050&currentDR=71&autoEatLevel=3&combatStyle=Melee&gameMode=Normal&yakSynergy=None&wastefulRing=No&guardianAmulet=No&stunDamage=Yes ) it suggests 79% damage reduction, but I have zero problems idling it at 71%, and that is measured out of combat, so before the combat triangle comes into play. It also seems odd that I would need a higher DR than the next dungeon, one more difficult than the WGD.

Is this correct?

**Comment by Silberdrachi** [comment]
Its suggesting that because of the increased damage due to the stuns. I would suggest checking the damage displayed in the window while you are stunned versus the damage displayed on CII. If those match then the site is working as intended. If that is the case, you can get lucky and not be stunned when you are at low health, and survive for a while. But on a long enough timeline you will die. 

If those numbers do not match, please send a screen shot of the game so i can try to look into the problem.

If you dont care about stun damage, theres also an advanced option on the CII site that lets you disable status damage increases, but be warned doing that could mean you will die.

**Comment by Silberdrachi** [comment]
Closing for lack of response
