### ISSUE TITLE
Take into account player attack speed for stun bonus damage

### ISSUE THREAD

**Issue by Delurielle** [Silberdrachi/CanIIdle#5]
The handling of stun is a bit wrong.

E.g. it seems like the Terran requirements (magic x 1020hp x 54dr) are based on "top damage attack while you're stunned". However, if one's attack speed is `< 3.9/1.33 = 2.92`, it's impossible to be attacked while stunned (3.9 for Terran's attack speed, 1.33 for his attack speed slow).

(An interesting side note is that if e.g. attack speed is 3, then to get dealt max damage, one would have to get hit by slow-stun-top damage in sequence, which has `0.15*0.2*0.1 = 0.3%` probability, which could actually be "safe enough" for many people, when combined with the extra improbability of having hp in kill range and the top damage attack rolling on the high end. But that's probably out of scope for this project.)

**Comment by Silberdrachi** [comment]
This is correct, but this is not a defect. Currently at this time CII does not support this level of calculation. This is something that i intend to add in the future when i have the time to properly implement it, but for now if you would like this level of accuracy you will need to use something like Combat Sim. 

This is mostly due to how to account for interesting interactions on how attack is reset when you are stunned and how that impacts slows. It is possible if you're on the edge of the attack speed window that it could or could not  impact you. Specifically how to handle that in a way that i can display to the user without making it confusing.

For the time being CII will be a worst case scenario application

**Comment by Delurielle** [comment]
I don't think that's correct. For the worst case, you don't need to think about attack speed edges/resets, and it's not as bad as the currently displayed worst case.

The deterministic worst-case is you start your attack at the moment you get stunned (you have the least possible amount of time to get yourself unstunned). In that case, the needed UI change is to get that player's attack speed, and the needed calculation change is the one I described (before going off-topic in the second part) - whether the player's attack speed, modified by any slows, is still faster than the enemy's. (Or N* faster than the enemy's if it's an N turn stun.)

(I guess you could think about e.g. "if your attack speed is 3.1 and the enemy's is 3, then to experience the worst case described above, you'd need to go through 30 rounds of combat, which might not happen", but I agree that would be too hard/complicated and unnecessary.)
