### ISSUE TITLE
Died despite the calculator saying I can idle (Turkul Giants)

### ISSUE THREAD

**Issue by Kvoo** [Silberdrachi/CanIIdle#8]
I double and triple checked my settings, i 100% should not have died. I also didn't run out of food.

Here's a Link: 

https://silberdrachi.github.io/CanIIdle/?totalHealth=6100&currentDR=19&autoEatLevel=2&combatStyle=Melee&gameMode=Adventure&yakSynergy=None&wastefulRing=No&guardianAmulet=No&stunDamage=Yes

Is there something not taken into account? The Area is arid plains, which has -40% food efficiency, but that shouldn't matter, should it?

**Comment by Silberdrachi** [comment]
This is way late but i just saw this. Sorry about that but there was an error.

I was calculating the lesser/greater sandstorm using the PLAYER health, not the ENEMY health. This left a small window where depending on your hp in relation to the enemy's hp, it could cause a player to die.

This will be fixed with the 1.0 OB Update.
